#!/usr/bin/env python3
"""Gate 12 — nothing that is ours disappears without an explicit decision.

Why this exists
---------------
On 2026-09-12 the 1.6.0 merge silently dropped two of our files:

    HermesMobile/Features/Chat/ToolCallCardView.swift
    HermesMobile/Features/Insights/InsightsRows.swift

Neither vanished because someone decided to remove it. They vanished because a
union of two trees took upstream's side of a hunk, and no gate looked at whether
what we had is still there. That is the failure this prevents.

How it decides what "ours" means
--------------------------------
`main` is our released branch; `upstream/master` is theirs. A symbol is ours when
it is declared in `main` and nowhere in `upstream/master`. A file is ours when it
exists in `main` and not in `upstream/master`.

What it checks
--------------
Every symbol declared in `main` must still be declared somewhere in the working
tree — regardless of which file it lives in, so a legitimate refactor that moves
a type between files passes. A removal is allowed only when it is written down in
`docs/agents/fork-manifest.json` under `removed`, with the reason. That turns a
silent loss into a decision someone made on purpose.

Symbols, not files, because a file can survive with its contents gutted: the merge
that took upstream's `ChatScrollPolicy.swift` kept the file and dropped thirteen
of our declarations inside it.

Usage
-----
    python3 scripts/check-fork-preserved.py             # gate
    python3 scripts/check-fork-preserved.py --list      # print what is ours
    python3 scripts/check-fork-preserved.py --record    # rewrite the manifest
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "docs" / "agents" / "fork-manifest.json"
OUR_BRANCH = "main"
THEIR_BRANCH = "upstream/master"

# Top-level type declarations only. A `let` inside a body is not a feature, and
# functions are too easy to rename in a legit refactor to be a stable identity.
DECL_RE = re.compile(
    r"^(?:@\w+(?:\([^)]*\))?\s+)*"
    r"(?:(?:public|internal|private|fileprivate|final|open|indirect)\s+)*"
    r"(?:struct|class|enum|actor|protocol)\s+(\w+)",
    re.M,
)


def git(*args: str) -> str:
    r = subprocess.run(["git", *args], cwd=ROOT, capture_output=True)
    # assets (.png/.svg) are binary; decode leniently rather than raise — only
    # .swift content is ever parsed.
    return r.stdout.decode("utf-8", errors="replace")


def tree_files(ref: str) -> list[str]:
    out = git("ls-tree", "-r", "--name-only", ref, "--", "HermesMobile/")
    return [f.strip() for f in out.splitlines() if f.strip()]


def show(ref: str, path: str) -> str:
    return git("show", f"{ref}:{path}")


def declared(text: str) -> set[str]:
    return set(DECL_RE.findall(text))


def ours() -> tuple[set[str], set[str]]:
    """(our files, our symbols) — present in main, absent from upstream."""
    def swift(ref: str) -> set[str]:
        return {f for f in tree_files(ref) if f.endswith(".swift")}

    our_files_all = set(tree_files(OUR_BRANCH))
    their_files_all = set(tree_files(THEIR_BRANCH))
    our_files = swift(OUR_BRANCH)
    their_files = swift(THEIR_BRANCH)

    files_only_ours = our_files - their_files

    symbols: set[str] = set()
    for path in sorted(our_files):
        text = show(OUR_BRANCH, path)
        symbols |= declared(text)

    their_symbols: set[str] = set()
    for path in sorted(their_files):
        their_symbols |= declared(show(THEIR_BRANCH, path))

    files_only_ours = our_files_all - their_files_all
    return files_only_ours, symbols - their_symbols


def current_symbols() -> set[str]:
    """Every type declared in the working tree."""
    found: set[str] = set()
    for path in ROOT.glob("HermesMobile/**/*.swift"):
        if "/.build/" in str(path):
            continue
        try:
            found |= declared(path.read_text(encoding="utf-8", errors="replace"))
        except OSError:
            continue
    return found


def load_manifest() -> dict:
    if MANIFEST.exists():
        try:
            return json.loads(MANIFEST.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            return {}
    return {}


def write_manifest(files: set[str], symbols: set[str], removed: list[str],
                   pending: list[str] | None = None) -> None:
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(
        json.dumps(
            {
                "_comment": (
                    "Generated by scripts/check-fork-preserved.py --record. "
                    "`removed` is the ONLY way a symbol may leave the tree: add "
                    "the name plus a reason, so the loss is a decision, not an "
                    "accident of a merge."
                ),
                "removed": sorted(removed),
                "pending_triage": sorted(pending or []),
                "our_files_at_record_time": sorted(files),
                "our_symbols_at_record_time": sorted(symbols),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def main() -> int:
    files, symbols = ours()

    if "--list" in sys.argv:
        print(f"our files (absent from {THEIR_BRANCH}): {len(files)}")
        for f in sorted(files):
            print(f"  {f}")
        print(f"\nour symbols (declared only in {OUR_BRANCH}): {len(symbols)}")
        for s in sorted(symbols):
            print(f"  {s}")
        return 0

    manifest = load_manifest()
    if "--record" in sys.argv:
        present = current_symbols()
        write_manifest(
            files,
            symbols,
            manifest.get("removed", []),
            sorted(symbols - present),
        )
        print(f"recorded {len(files)} file(s), {len(symbols)} symbol(s)")
        return 0

    removed = set(manifest.get("removed", []))
    # The 1.6.0 merge dropped these before this gate existed. They are baselined
    # so the gate is usable today: a NEW disappearance is a blocker, and the
    # legacy set is reported every run until each one is restored or recorded.
    pending = set(manifest.get("pending_triage", []))
    present = current_symbols()

    missing = sorted(symbols - present)
    regressions = [n for n in missing if n not in removed and n not in pending]
    legacy = [n for n in missing if n in pending]

    print("[12/12] fork-owned symbols still present")
    if regressions:
        print(f"      BLOCKER: {len(regressions)} own declaration(s) vanished")
        for name in regressions[:20]:
            print(f"        {name}")
        if len(regressions) > 20:
            print(f"        ... and {len(regressions) - 20} more")
        print("      A union took upstream's side of a hunk and dropped ours.")
        print("      Restore it, or record the removal with a reason in")
        print("      docs/agents/fork-manifest.json (`removed`).")
        return 1

    note = f", {len(removed)} recorded removal(s)" if removed else ""
    if legacy:
        print(f"      warn  {len(legacy)} declaration(s) still missing from the "
              f"1.6.0 merge — see fork-manifest.json `pending_triage`")
        for name in legacy[:8]:
            print(f"        {name}")
        if len(legacy) > 8:
            print(f"        ... and {len(legacy) - 8} more")
    print(f"      ok  {len(symbols)} own declaration(s) present{note}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
